from typing import Protocol

from .models import GuestResponse, Invitation


class RSVPStore(Protocol):
    def save_invitation(self, invitation: Invitation) -> None: ...
    def list_invitations(self, owner_email: str) -> list[Invitation]: ...
    def get_invitation(self, invitation_id: str) -> Invitation | None: ...
    def save_response(self, response: GuestResponse) -> None: ...
    def get_response_by_token(self, invitation_id: str, manage_token: str) -> GuestResponse | None: ...
